#!/bin/bash

set -eo pipefail

NOTEBOOK_ARGS=

if [ x"${JUPYTER_NOTEBOOK_PASSWORD}" != x"" ]; then
    NOTEBOOK_ARGS=--NotebookApp.password=`python -c "import notebook.auth; \
        print(notebook.auth.passwd(\"$JUPYTER_NOTEBOOK_PASSWORD\"))"`
    unset JUPYTER_NOTEBOOK_PASSWORD
fi

exec /usr/local/bin/start-notebook.sh $NOTEBOOK_ARGS
